spring.application.name=GestionCommande
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gestion_clients;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8082
logging.level.org.springframework.security=DEBUG
